name: Build APK BRI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-setuptools libffi-dev libssl-dev

      - name: Install Buildozer
        run: pip3 install --user buildozer cython==0.29.33

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hasil_APK_BRI
          path: bin/*.apk
