name: Build APK BRI
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-setuptools libffi-dev libssl-dev
          pip3 install --user buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Menghapus sisa build lama agar bersih
          rm -rf .buildozer
          # Jalankan build
          buildozer -v android debug
        env:
          ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hasil_APK_BRI
          path: bin/*.apk
